import './globals.css';
import '../style/index.scss';
import AppProvider from '@/contextApi/AppProvider';
import ReduxProvider from '@/redux/provider';
import { ToastContainer } from 'react-toastify';
import { childrenType } from '@/interFace/interFace';
import { Be_Vietnam_Pro } from 'next/font/google';
const beVietnamPro = Be_Vietnam_Pro({
    subsets: ['latin', 'vietnamese'],
    weight: ['400', '500', '600', '700', '900'],
    display: 'swap',
});

export default function RootLayout({ children }: childrenType) {
    return (
        <>
            <html lang="en" className={beVietnamPro.className}>
                <head>
                    <meta httpEquiv="x-ua-compatible" content="ie=edge" />
                    <meta name="description" content="Generated by create next app" />
                    <meta name="robots" content="noindex, follow" />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1, shrink-to-fit=no"
                    />
                    <title>Grow Sphere</title>
                    <link rel="icon" href="/favicon.png" />
                </head>

                <body suppressHydrationWarning={true}>
                    <ReduxProvider>
                        <AppProvider>{children}</AppProvider>
                        <ToastContainer
                            position="top-right"
                            autoClose={1000}
                            hideProgressBar={false}
                            newestOnTop={false}
                            closeOnClick
                            rtl={false}
                            pauseOnFocusLoss
                            draggable
                            pauseOnHover
                            theme="light"
                        />
                    </ReduxProvider>
                </body>
            </html>
        </>
    );
}
